Added type hints
lattkkthxbbye/aryas pull request #37
Opened 2017-06-03 23:49 UTC by NatKarmios

2017-06-03 23:53 UTC, NatKarmios commented
This should hopefully fix all the dupe commits.

2017-06-04 00:35 UTC, tom-sherman requested changes
Keep in function param hints where the value could be ambiguous, remove otherwise.

2017-06-04 00:35 UTC, tom-sherman commented on src/utility.py
> +async def send(bot: commands.Bot, message: str, channel: Channel, delete: bool=False,
Remove `delete` hint

2017-06-04 00:35 UTC, tom-sherman commented on src/utility.py
> +               time: float=MESSAGE_SLEEP_TIME) -> None:
Remove `time` hint

2017-06-04 00:35 UTC, tom-sherman commented on src/globals.py
> +possible_status: Set[str] = {'away', 'vacation', 'active'}
Remove hint

2017-06-04 00:35 UTC, tom-sherman commented on src/globals.py
> +logger: logging.Logger = logging.getLogger('discord')
Remove hint

2017-06-04 00:35 UTC, tom-sherman commented on src/extensions/modtools.py
> +    async def ban(self, ctx: commands.Context, member: discord.Member, reason: str) -> None:
Remove `reason` hint

2017-06-04 00:35 UTC, tom-sherman commented on src/extensions/modtools.py
> +    async def kick(self, ctx: commands.Context, member: discord.Member, reason: str) -> None:
Remove `reason` hint

2017-06-04 00:35 UTC, tom-sherman commented on src/extensions/general.py
> +    async def weather(self, ctx: commands.Context, country: str, city: str) -> None:
Remove `city` and `country` hint

2017-06-04 00:35 UTC, tom-sherman commented on src/extensions/general.py
> +    async def ping(self, ctx) -> None:
Add a hint for `ctx`

2017-06-04 09:16 UTC, merged