Created the events cog for event handling
lattkkthxbbye/aryas pull request #40
Opened 2017-06-04 09:26 UTC by BlackTiger1500

Created an event cog for event handling with 'on_message' event and updated aryas.py for startup extensions

2017-06-04 09:47 UTC, tom-sherman requested changes

2017-06-04 09:47 UTC, tom-sherman commented on src/extensions/events.py
> +            await self.bot.kick(message.author)
Put this code in a shared method that is called here and in the `?kick` command, or invoke the `kick` method directly.

Use the private message text as the reason for the kick.

2017-06-04 09:47 UTC, tom-sherman commented on src/extensions/events.py
> +  async def on_message(self, message):
At present, this coroutine is not very extendable. Let's have a discussion on the best way to make this more maintainable

2017-06-04 18:51 UTC, tom-sherman requested changes

2017-06-04 18:51 UTC, tom-sherman commented on src/utility.py
> +async def kick_user(user, mod, server, bot, reason):
Add docstrings for this function

2017-06-04 18:51 UTC, tom-sherman commented on src/utility.py
> +        await bot.ban(message.author)
This needs to be kick, not ban

2017-06-04 18:51 UTC, tom-sherman commented on src/utility.py
> +        await bot.send_message(channel, 'Failed to kick {} for {}'.format(user, reason))
Use the `send` function in this file.

2017-06-04 18:51 UTC, tom-sherman commented on src/utility.py
> +        print(e)
Use the logger, don't print to stdout

2017-06-04 18:51 UTC, tom-sherman commented on src/utility.py
> +    channel = discord.utils.get(server.channels, name='mod_log')
Remove this line for now, address it in subsequent pull request

2017-06-04 18:51 UTC, tom-sherman commented on src/extensions/events.py
> +         if re.search(pattern, message.content):
Add comments to explain the process of what the bot is doing. First he deletes, then messages, then kicks etc.

2017-06-04 18:51 UTC, tom-sherman commented on src/extensions/events.py
> +    await self.bot.process_commands(message)
Add a comment explaining why we need this.

2017-06-05 18:18 UTC, BlackTiger1500 commented on src/utility.py
> +async def kick_user(user, mod, server, bot, reason):
Done

2017-06-05 18:18 UTC, BlackTiger1500 commented on src/utility.py
> +        await bot.ban(message.author)
Fixed

2017-06-05 18:27 UTC, BlackTiger1500 commented on src/utility.py
> +        await bot.send_message(channel, 'Failed to kick {} for {}'.format(user, reason))
Done

2017-06-05 19:38 UTC, tom-sherman approved these changes

2017-06-05 19:40 UTC, tom-sherman commented
This has now been merged.

2017-06-05 19:40 UTC, closed without merging